# Generated by Django 6.1 on 2026-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=5)),
                ('price', models.DecimalField()),
                ('Stock_Quantity', models.IntegerField()),
                ('Availability_Status', models.CharField(max_length=20)),
                ('Date_Added', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
            ],
        ),
    ]
