# Generated by Django 6.1 on 2026-09-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HOT', 'Hot Drinks'), ('COLD', 'Cold Drinks'), ('PASTRY', 'Pastries'), ('SNACK', 'Snacks')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT', 'Out of Stock')], default='AVAILABLE', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
