# Generated by Django 6.1 on 2026-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_item_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock_Quantity', models.IntegerField()),
                ('Availability_Status', models.CharField(max_length=20)),
                ('Date_Added', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
